export enum EventType {
  PRODUCT_VIEWED = 'PRODUCT_VIEWED',
  PRODUCT_CREATED = 'PRODUCT_CREATED',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_PAID = 'ORDER_PAID',
  USER_REGISTERED = 'USER_REGISTERED',
  SEARCH_PERFORMED = 'SEARCH_PERFORMED',
}
